"""End-to-end pipeline:  raw CSV -> panel -> LOOCV leaderboard -> best model -> report figures.

Usage:  python -m src.train
"""
import json
import joblib
import numpy as np
import pandas as pd

from .config import load_config, resolve
from .data import load_raw, to_wide, quality_scorecard
from .features import build_modeling_frame, feature_columns
from .models import build_pipeline, leaderboard, oof_predictions
from . import visualize as viz


def main():
    cfg = load_config()
    np.random.seed(cfg["project"]["seed"])
    m = cfg["modeling"]

    # 1. Data ---------------------------------------------------------------
    raw = load_raw(resolve(cfg, "raw_data"), cfg["data"]["missing_token"])
    wide = to_wide(raw)
    frame = build_modeling_frame(wide, cfg)
    wide.to_csv(resolve(cfg, "panel_wide"), index=False)
    frame.to_csv(resolve(cfg, "modeling_frame"), index=False)
    scorecard = quality_scorecard(wide, cfg["data"]["national_columns"])
    print(f"panel {wide.shape} | modeling frame {frame.shape}")

    # 2. Models (LOOCV) -----------------------------------------------------
    X, y = frame[feature_columns(cfg)], frame[m["target"]]
    lb = leaderboard(cfg, X, y)
    print(lb.round(3).to_string(index=False))

    # 3. Fit + persist every model; best (by LOOCV R2) is the served one -------
    models_dir = resolve(cfg, "models_dir")
    for key in m["models"]:
        joblib.dump(build_pipeline(key, cfg).fit(X, y), models_dir / f"{key}.joblib")
    best_key = lb.loc[lb[m["selection_metric"]].idxmax(), "key"]
    best = joblib.load(models_dir / f"{best_key}.joblib")
    joblib.dump(best, resolve(cfg, "best_model"))

    metrics = {"best_model": best_key, "n_train_rows": int(len(frame)),
               "seed": cfg["project"]["seed"], "cv": m["cv"],
               "leaderboard": lb.drop(columns="key").round(4).to_dict(orient="records")}
    with open(resolve(cfg, "metrics"), "w") as f:
        json.dump(metrics, f, indent=2)

    # 4. Reports ------------------------------------------------------------
    reports, figs = resolve(cfg, "reports_dir"), resolve(cfg, "figures_dir")
    colors = cfg["plot"]["country_colors"]
    lb.to_csv(reports / "model_leaderboard.csv", index=False)
    scorecard.to_csv(reports / "data_quality_scorecard.csv")

    viz.plot_stock_trajectories(wide, colors, figs / "01_stock_trajectories.png")
    viz.plot_growth(wide, colors, figs / "02_growth_since_2000.png")
    viz.plot_uae(wide, colors["UAE"], figs / "03_uae_reversal.png")
    viz.plot_macro_collinearity(wide, figs / "04_macro_collinearity.png")
    viz.plot_leaderboard(lb, figs / "05_leaderboard.png")
    oof = oof_predictions(build_pipeline("linear_regression", cfg), X, y)
    viz.plot_residuals(frame[["Year", "Destination_Country"]], y.values - oof, colors,
                       figs / "06_residuals_linear.png")

    write_summary(cfg, wide, frame, lb, best_key, oof, y, reports / "summary.md")
    print(f"best model: {best_key} -> {resolve(cfg, 'best_model')}")


def write_summary(cfg, wide, frame, lb, best_key, oof, y, path):
    piv = viz.stock_pivot(wide)
    growth = ((piv.loc[2024] / piv.loc[2000] - 1) * 100).dropna().sort_values(ascending=False)
    uae = piv["UAE"].dropna()
    macro = wide.drop_duplicates("Year")
    corr = {c: macro["Year"].corr(macro[c]) for c in ["GDP_India", "Remittance_USD_Billion", "Unemployment_India"]}
    resid = pd.Series(y.values - oof, index=frame.index).abs()
    worst = frame.loc[resid.sort_values(ascending=False).index[:3], ["Year", "Destination_Country"]]
    worst_txt = ", ".join(f"{r.Destination_Country} {int(r.Year)}" for r in worst.itertuples())
    table = _md_table(lb.drop(columns="key").round(3))

    text = f"""# Results summary (auto-generated by `python -m src.train`)

**Modeling frame:** {len(frame)} rows with an observed `Total_Indian_Migrants`; CV = leave-one-out.
**Served model:** `{best_key}` (highest LOOCV R2).

## Leaderboard
{table}

![leaderboard](figures/05_leaderboard.png)

## Findings
- **Growth 2000-2024:** {", ".join(f"{k} +{v:.0f}%" for k, v in growth.items())}.
- **UAE reversal:** peaked at {uae.max():,.0f} in {uae.idxmax()}, fell to {uae.iloc[-1]:,.0f} by {uae.index[-1]} ({(uae.iloc[-1]/uae.max()-1)*100:+.1f}%), the only contraction in the panel.
- **Collinearity with Year:** GDP r={corr['GDP_India']:.2f}, remittances r={corr['Remittance_USD_Billion']:.2f}, unemployment r={corr['Unemployment_India']:.2f}. GDP and remittances are excluded from the model for this reason; unemployment is only moderately time-bound (|r| < 0.7) and is kept, but its effect is hard to separate from the trend at n=35.
- **Largest LOOCV errors (linear):** {worst_txt}.

![trajectories](figures/01_stock_trajectories.png)
![growth](figures/02_growth_since_2000.png)
![uae](figures/03_uae_reversal.png)
![macro](figures/04_macro_collinearity.png)
![residuals](figures/06_residuals_linear.png)

## Limitations
- Only {len(frame)} labelled rows; the model describes the pooled trend and is not a calibrated forecaster.
- `Unemployment_India` is national, so it varies only by year, not by destination.
"""
    path.write_text(text)


def _md_table(df: pd.DataFrame) -> str:
    """Minimal markdown table (avoids a tabulate dependency)."""
    head = "| " + " | ".join(df.columns) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *rows])


if __name__ == "__main__":
    main()
